create table boot_notification (iccid varchar(255) not null auto_increment, charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), firmware_version varchar(255), imsi varchar(255), meter_serial_number varchar(255), meter_type varchar(255), primary key (iccid)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
create table boot_notification (iccid varchar(255) not null auto_increment, charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), firmware_version varchar(255), imsi varchar(255), meter_serial_number varchar(255), meter_type varchar(255), primary key (iccid)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
create table boot_notification (iccid varchar(255) not null auto_increment, charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), firmware_version varchar(255), imsi varchar(255), meter_serial_number varchar(255), meter_type varchar(255), primary key (iccid)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
create table boot_notification (iccid varchar(255) not null auto_increment, charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), firmware_version varchar(255), imsi varchar(255), meter_serial_number varchar(255), meter_type varchar(255), primary key (iccid)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
create table boot_notification (iccid varchar(255) not null, charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), firmware_version varchar(255), imsi varchar(255), meter_serial_number varchar(255), meter_type varchar(255), primary key (iccid)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
create table boot_notification (iccid varchar(255) not null auto_increment, charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), firmware_version varchar(255), imsi varchar(255), meter_serial_number varchar(255), meter_type varchar(255), primary key (iccid)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
create table boot_notification (iccid varchar(255) not null, charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), firmware_version varchar(255), imsi varchar(255), meter_serial_number varchar(255), meter_type varchar(255), primary key (iccid)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table hibernate_sequence (next_val bigint) engine=MyISAM
insert into hibernate_sequence values ( 1 )
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
create table boot_notification (iccid varchar(255) not null, charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), firmware_version varchar(255), imsi varchar(255), meter_serial_number varchar(255), meter_type varchar(255), primary key (iccid)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table hibernate_sequence (next_val bigint) engine=MyISAM
insert into hibernate_sequence values ( 1 )
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
create table boot_notification (iccid varchar(255) not null, charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), firmware_version varchar(255), imsi varchar(255), meter_serial_number varchar(255), meter_type varchar(255), primary key (iccid)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
create table boot_notification (iccid varchar(255) not null, charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), firmware_version varchar(255), imsi varchar(255), meter_serial_number varchar(255), meter_type varchar(255), primary key (iccid)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table hibernate_sequence (next_val bigint) engine=MyISAM
insert into hibernate_sequence values ( 1 )
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
create table boot_notification (iccid varchar(255) not null, charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), firmware_version varchar(255), imsi varchar(255), meter_serial_number varchar(255), meter_type varchar(255), primary key (iccid)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table hibernate_sequence (next_val bigint) engine=MyISAM
insert into hibernate_sequence values ( 1 )
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
create table address (address_pk integer not null auto_increment, city varchar(255), country varchar(255), house_number varchar(255), street varchar(255), zip_code varchar(255), primary key (address_pk)) engine=MyISAM
create table charge_box (charge_box_pk integer not null auto_increment, admin_address varchar(255), charge_box_id varchar(255), charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), description varchar(255), diagnostics_status varchar(255), diagnostics_timestamp datetime, endpoint_address varchar(255), fw_update_status varchar(255), fw_update_timestamp datetime, fw_version float, iccid varchar(255), imsi varchar(255), insert_connector_status_after_transaction_msg integer, last_heartbeat_timestamp datetime, location_latitude float, location_longitude float, meter_serial_number varchar(255), meter_type varchar(255), note varchar(255), ocpp_protocol varchar(255), address_pk integer, primary key (charge_box_pk)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
alter table charge_box add constraint FK9067qhmmvocmc9qovixikqrcq foreign key (address_pk) references address (address_pk)
create table address (address_pk integer not null auto_increment, city varchar(255), country varchar(255), house_number varchar(255), street varchar(255), zip_code varchar(255), primary key (address_pk)) engine=MyISAM
create table charge_box (charge_box_pk integer not null auto_increment, admin_address varchar(255), charge_box_id varchar(255), charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), description varchar(255), diagnostics_status varchar(255), diagnostics_timestamp datetime, endpoint_address varchar(255), fw_update_status varchar(255), fw_update_timestamp datetime, fw_version float, iccid varchar(255), imsi varchar(255), insert_connector_status_after_transaction_msg integer, last_heartbeat_timestamp datetime, location_latitude float, location_longitude float, meter_serial_number varchar(255), meter_type varchar(255), note varchar(255), ocpp_protocol varchar(255), address_pk integer, primary key (charge_box_pk)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
alter table charge_box add constraint FK9067qhmmvocmc9qovixikqrcq foreign key (address_pk) references address (address_pk)
create table address (address_pk integer not null auto_increment, city varchar(255), country varchar(255), house_number varchar(255), street varchar(255), zip_code varchar(255), primary key (address_pk)) engine=MyISAM
create table charge_box (charge_box_pk integer not null auto_increment, admin_address varchar(255), charge_box_id varchar(255), charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), description varchar(255), diagnostics_status varchar(255), diagnostics_timestamp datetime, endpoint_address varchar(255), fw_update_status varchar(255), fw_update_timestamp datetime, fw_version float, iccid varchar(255), imsi varchar(255), insert_connector_status_after_transaction_msg integer, last_heartbeat_timestamp datetime, location_latitude float, location_longitude float, meter_serial_number varchar(255), meter_type varchar(255), note varchar(255), ocpp_protocol varchar(255), address_pk integer, primary key (charge_box_pk)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
alter table charge_box add constraint FK9067qhmmvocmc9qovixikqrcq foreign key (address_pk) references address (address_pk)
create table address (address_pk integer not null auto_increment, city varchar(255), country varchar(255), house_number varchar(255), street varchar(255), zip_code varchar(255), primary key (address_pk)) engine=MyISAM
create table charge_box (charge_box_pk integer not null auto_increment, admin_address varchar(255), charge_box_id varchar(255), charge_box_serial_number varchar(255), charge_point_model varchar(255), charge_point_serial_number varchar(255), charge_point_vendor varchar(255), description varchar(255), diagnostics_status varchar(255), diagnostics_timestamp datetime, endpoint_address varchar(255), fw_update_status varchar(255), fw_update_timestamp datetime, fw_version float, iccid varchar(255), imsi varchar(255), insert_connector_status_after_transaction_msg integer, last_heartbeat_timestamp datetime, location_latitude float, location_longitude float, meter_serial_number varchar(255), meter_type varchar(255), note varchar(255), ocpp_protocol varchar(255), address_pk integer, primary key (charge_box_pk)) engine=MyISAM
create table charge_point (charge_point_id integer not null auto_increment, address_line1 varchar(255), address_line2 varchar(255), city varchar(255), latitude float, longitude float, postal_code integer, state varchar(255), primary key (charge_point_id)) engine=MyISAM
create table user (id integer not null auto_increment, email varchar(255), first_name varchar(255), isflaged bit, last_name varchar(255), phoneno varchar(255), primary key (id)) engine=MyISAM
alter table charge_box add constraint FK9067qhmmvocmc9qovixikqrcq foreign key (address_pk) references address (address_pk)
